import React, { useState, useRef, useEffect } from 'react';
import DashboardLayout from '../components/DashboardLayout';
import { Search, Filter, Plus, FileText, FileSpreadsheet, Eye, Download, CheckCircle, Clock, X, AlertTriangle, ShieldCheck } from 'lucide-react';
import CustomDropdown from '../components/CustomDropdown';
import { motion, AnimatePresence } from 'framer-motion';

const DocumentLibrary = () => {
  const [documents, setDocuments] = useState([
    { id: 1, name: 'Security Policy 2024.pdf', size: '2.4 MB', type: 'PDF', user: 'John Smith', date: 'Mar 15, 2024', status: 'Completed', findings: 23, risk: 'Critical' },
    { id: 2, name: 'Compliance Report Q1.docx', size: '1.8 MB', type: 'DOCX', user: 'Emily Davis', date: 'Mar 14, 2024', status: 'Processing', findings: '-', risk: 'Pending' },
    { id: 3, name: 'Risk Assessment Matrix.xlsx', size: '945 KB', type: 'XLSX', user: 'Mike Wilson', date: 'Mar 13, 2024', status: 'Completed', findings: 8, risk: 'Medium' },
  ]);
  const fileInputRef = useRef(null);
  const [selectedDoc, setSelectedDoc] = useState(null);
  const [isSidePanelOpen, setIsSidePanelOpen] = useState(false);

  const handleDownload = (doc) => {
    const content = `COMPANY NAME: Acme Corporation\n\nREPORT DETAILS\n-------------------\nDocument Name: ${doc.name}\nType: ${doc.type}\nUploaded By: ${doc.user}\nUpload Date: ${doc.date}\nStatus: ${doc.status}\nFindings: ${doc.findings}\nRisk Level: ${doc.risk}\n\nSUMMARY:\nThis report is automatically generated by the Compliance platform. The system has analyzed ${doc.name} against the latest frameworks. Please review all critical findings.`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${doc.name.split('.')[0]}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleView = (doc) => {
    setSelectedDoc(doc);
    setIsSidePanelOpen(true);
  };

  const handleFileUpload = (e) => {
    const files = Array.from(e.target.files);
    if (!files.length) return;
    
    const newDocs = files.map(file => {
      const ext = file.name.split('.').pop().toUpperCase() || 'DOC';
      return {
        id: Math.random(),
        name: file.name,
        size: (file.size / (1024 * 1024)).toFixed(1) + ' MB',
        type: ext,
        user: 'John Smith',
        date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
        status: 'Completed',
        findings: 0,
        risk: 'Low'
      };
    });
    
    setDocuments(prev => [...newDocs, ...prev]);
  };

  return (
    <DashboardLayout>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '2rem' }}>
        <div>
          <h1 style={{ fontSize: '1.75rem', marginBottom: '0.25rem', color: 'var(--text-main)' }}>Document Library</h1>
          <p style={{ color: 'var(--text-muted)' }}>Manage and review your security documents</p>
        </div>
        <button onClick={() => fileInputRef.current?.click()} className="btn btn-secondary" style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', cursor: 'pointer' }}>
          <input type="file" multiple ref={fileInputRef} onChange={handleFileUpload} style={{ display: 'none' }} />
          <Plus size={20} /> Upload Document
        </button>
      </div>

      <div className="card" style={{ background: '#fff', border: '1px solid #e2e8f0', marginBottom: '2rem' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'minmax(250px, 2fr) 1fr 1fr', gap: '1.5rem' }}>
          <div>
             <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: '#475569', fontWeight: 500 }}>Search Documents</label>
             <div style={{ position: 'relative' }}>
               <Search size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: '#94a3b8' }} />
               <input type="text" placeholder="Search by document name..." style={{ width: '100%', padding: '0.6rem 1rem 0.6rem 2.5rem', borderRadius: '8px', border: '1px solid #e2e8f0' }} />
             </div>
          </div>
          <div>
             <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: '#475569', fontWeight: 500 }}>Date Range</label>
             <CustomDropdown options={['All Time', 'Last 7 Days', 'Last 30 Days']} width="100%" />
          </div>
          <div>
             <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: '#475569', fontWeight: 500 }}>Risk Level</label>
             <CustomDropdown options={['All Levels', 'Critical', 'High']} width="100%" />
          </div>
        </div>
      </div>

      <div className="card" style={{ background: '#fff', border: '1px solid #e2e8f0', padding: 0, overflow: 'hidden' }}>
        <div style={{ padding: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #e2e8f0' }}>
          <h2 style={{ fontSize: '1.25rem', color: '#1e293b' }}>Documents <span style={{ color: '#94a3b8', fontSize: '1rem', fontWeight: 'normal' }}>(247 total)</span></h2>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span style={{ fontSize: '0.9rem', color: '#64748b' }}>Show:</span>
            <CustomDropdown options={['25', '50']} width="80px" />
          </div>
        </div>
        
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
          <thead>
            <tr style={{ borderBottom: '1px solid #e2e8f0', color: '#64748b', fontSize: '0.85rem' }}>
              <th style={{ padding: '1rem 1.5rem', fontWeight: 600 }}>Document Name</th>
              <th style={{ padding: '1rem 1.5rem', fontWeight: 600 }}>Type</th>
              <th style={{ padding: '1rem 1.5rem', fontWeight: 600 }}>Uploaded By</th>
              <th style={{ padding: '1rem 1.5rem', fontWeight: 600 }}>Upload Date</th>
              <th style={{ padding: '1rem 1.5rem', fontWeight: 600 }}>Status</th>
              <th style={{ padding: '1rem 1.5rem', fontWeight: 600 }}>Findings</th>
              <th style={{ padding: '1rem 1.5rem', fontWeight: 600 }}>Risk Level</th>
              <th style={{ padding: '1rem 1.5rem', fontWeight: 600, textAlign: 'right' }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {documents.map((doc) => (
              <tr key={doc.id} style={{ borderBottom: '1px solid #e2e8f0', color: '#1e293b' }}>
                <td style={{ padding: '1.25rem 1.5rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                    {doc.type === 'PDF' && <FileText color="#ef4444" />}
                    {doc.type === 'DOCX' && <FileText color="#3b82f6" />}
                    {doc.type === 'XLSX' && <FileSpreadsheet color="#10b981" />}
                    <div>
                      <div style={{ fontWeight: 500 }}>{doc.name}</div>
                      <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>{doc.size}</div>
                    </div>
                  </div>
                </td>
                <td style={{ padding: '1.25rem 1.5rem' }}>
                  <span style={{ padding: '0.25rem 0.5rem', background: '#f1f5f9', borderRadius: '4px', fontSize: '0.75rem', fontWeight: 600, color: '#475569' }}>{doc.type}</span>
                </td>
                <td style={{ padding: '1.25rem 1.5rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${doc.user}`} alt={doc.user} style={{ width: '28px', height: '28px', borderRadius: '50%', background: '#f1f5f9' }} />
                    <span style={{ fontSize: '0.9rem' }}>{doc.user}</span>
                  </div>
                </td>
                <td style={{ padding: '1.25rem 1.5rem', fontSize: '0.9rem', color: '#475569' }}>{doc.date}</td>
                <td style={{ padding: '1.25rem 1.5rem' }}>
                  {doc.status === 'Completed' ? (
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.25rem', padding: '0.25rem 0.75rem', background: '#ecfdf5', color: '#059669', borderRadius: '20px', fontSize: '0.8rem', fontWeight: 500 }}>
                      <CheckCircle size={14} /> Completed
                    </span>
                  ) : (
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.25rem', padding: '0.25rem 0.75rem', background: '#fef3c7', color: '#d97706', borderRadius: '20px', fontSize: '0.8rem', fontWeight: 500 }}>
                      <Clock size={14} /> Processing
                    </span>
                  )}
                </td>
                <td style={{ padding: '1.25rem 1.5rem', fontWeight: 500 }}>{doc.findings}</td>
                <td style={{ padding: '1.25rem 1.5rem' }}>
                  <span style={{ 
                    padding: '0.25rem 0.75rem', 
                    borderRadius: '20px', 
                    fontSize: '0.8rem', 
                    fontWeight: 600,
                    background: doc.risk === 'Critical' ? '#fee2e2' : doc.risk === 'Medium' ? '#fef3c7' : '#f1f5f9',
                    color: doc.risk === 'Critical' ? '#dc2626' : doc.risk === 'Medium' ? '#d97706' : '#64748b'
                  }}>{doc.risk}</span>
                </td>
                <td style={{ padding: '1.25rem 1.5rem', textAlign: 'right' }}>
                  <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', color: '#94a3b8' }}>
                    <button onClick={() => handleView(doc)} style={{ background: 'none', border: 'none', padding: 0, color: 'inherit', cursor: 'pointer' }}><Eye size={18} /></button>
                    <button onClick={() => handleDownload(doc)} style={{ background: 'none', border: 'none', padding: 0, color: 'inherit', cursor: 'pointer' }}><Download size={18} /></button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        
        <div style={{ padding: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid #e2e8f0', color: '#64748b', fontSize: '0.9rem' }}>
          <div>Showing 1 to 25 of 247 results</div>
          <div style={{ display: 'flex', gap: '0.25rem' }}>
            <button style={{ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid #e2e8f0', borderRadius: '6px', background: '#fff', cursor: 'pointer' }}>{'<'}</button>
            <button style={{ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid currentColor', borderRadius: '6px', background: '#2563eb', color: '#fff', cursor: 'pointer' }}>1</button>
            <button style={{ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid #e2e8f0', borderRadius: '6px', background: '#fff', cursor: 'pointer' }}>2</button>
            <button style={{ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid #e2e8f0', borderRadius: '6px', background: '#fff', cursor: 'pointer' }}>3</button>
            <button style={{ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid #e2e8f0', borderRadius: '6px', background: '#fff', cursor: 'pointer' }}>{'>'}</button>
          </div>
        </div>
      </div>

      <AnimatePresence>
        {isSidePanelOpen && selectedDoc && (
          <>
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 0.5 }}
              exit={{ opacity: 0 }}
              style={{ position: 'fixed', inset: 0, background: '#0f172a', zIndex: 100 }}
              onClick={() => setIsSidePanelOpen(false)}
            />
            <motion.div 
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              style={{ position: 'fixed', top: 0, right: 0, bottom: 0, width: '450px', background: '#fff', zIndex: 101, display: 'flex', flexDirection: 'column', boxShadow: '-4px 0 15px rgba(0,0,0,0.1)' }}
            >
              <div style={{ padding: '1.5rem', borderBottom: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <h2 style={{ fontSize: '1.25rem', color: '#1e293b', fontWeight: 600 }}>Document Analysis</h2>
                <button onClick={() => setIsSidePanelOpen(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '0.25rem', display: 'flex' }}><X size={20} color="#64748b" /></button>
              </div>
              <div style={{ padding: '1.5rem', flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
                 
                 <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                   <div style={{ width: '48px', height: '48px', background: '#eff6ff', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#2563eb', flexShrink: 0 }}>
                      <FileText size={24} />
                   </div>
                   <div>
                     <h3 style={{ fontSize: '1.1rem', color: '#1e293b', marginBottom: '0.25rem', fontWeight: 600 }}>{selectedDoc.name}</h3>
                     <div style={{ color: '#64748b', fontSize: '0.85rem' }}>{selectedDoc.size} • Uploaded by {selectedDoc.user} on {selectedDoc.date}</div>
                   </div>
                 </div>

                 <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                    <div style={{ padding: '1rem', background: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
                       <div style={{ color: '#64748b', fontSize: '0.85rem', marginBottom: '0.5rem' }}>Risk Level</div>
                       <div style={{ color: selectedDoc.risk === 'Critical' ? '#dc2626' : selectedDoc.risk === 'Medium' ? '#d97706' : '#059669', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                          <AlertTriangle size={16} /> {selectedDoc.risk}
                       </div>
                    </div>
                    <div style={{ padding: '1rem', background: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
                       <div style={{ color: '#64748b', fontSize: '0.85rem', marginBottom: '0.5rem' }}>Findings</div>
                       <div style={{ color: '#1e293b', fontWeight: 600, fontSize: '1.1rem' }}>{selectedDoc.findings} Issues</div>
                    </div>
                 </div>

                 <div>
                    <h4 style={{ color: '#1e293b', fontSize: '1rem', marginBottom: '1rem', fontWeight: 600, borderBottom: '1px solid #e2e8f0', paddingBottom: '0.5rem' }}>System Summary</h4>
                    <p style={{ color: '#475569', fontSize: '0.9rem', lineHeight: 1.6 }}>
                      The AI compliance engine has successfully crawled and parsed this document against 4 active frameworks. Text extraction confidence is rated at 98%.
                    </p>
                 </div>

                 <div>
                    <h4 style={{ color: '#1e293b', fontSize: '1rem', marginBottom: '1rem', fontWeight: 600, borderBottom: '1px solid #e2e8f0', paddingBottom: '0.5rem' }}>Key Flagged Entries</h4>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                       <div style={{ background: '#fef2f2', borderLeft: '3px solid #dc2626', padding: '1rem', borderRadius: '4px' }}>
                          <div style={{ color: '#991b1b', fontWeight: 600, fontSize: '0.9rem', marginBottom: '0.25rem' }}>Confidentiality Clause - Page 4</div>
                          <div style={{ color: '#b91c1c', fontSize: '0.85rem' }}>Missing GDPR disclosure regarding data processing jurisdiction.</div>
                       </div>
                       <div style={{ background: '#fffbeb', borderLeft: '3px solid #d97706', padding: '1rem', borderRadius: '4px' }}>
                          <div style={{ color: '#b45309', fontWeight: 600, fontSize: '0.9rem', marginBottom: '0.25rem' }}>Liability Limitation - Page 12</div>
                          <div style={{ color: '#d97706', fontSize: '0.85rem' }}>Cap on damages deviates from SOC 2 standard recommendations.</div>
                       </div>
                    </div>
                 </div>

              </div>
              <div style={{ padding: '1.25rem 1.5rem', borderTop: '1px solid #e2e8f0', background: '#f8fafc', display: 'flex', gap: '1rem' }}>
                 <button className="btn btn-outline" style={{ flex: 1, background: '#fff', border: '1px solid #cbd5e1', color: '#475569', fontWeight: 600, padding: '0.6rem', borderRadius: '6px', cursor: 'pointer' }} onClick={() => setIsSidePanelOpen(false)}>Close panel</button>
                 <button className="btn btn-primary" style={{ flex: 1, background: '#2563eb', color: '#fff', display: 'flex', justifyContent: 'center', gap: '0.5rem', alignItems: 'center', padding: '0.6rem', borderRadius: '6px', cursor: 'pointer', border: 'none' }}>
                    <ShieldCheck size={18} /> Resolve Risks
                 </button>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </DashboardLayout>
  );
};

export default DocumentLibrary;
